export const colors = {
  background: "#fff8f7",
  cream: "#fff8f7",
  ivory: "#fdf1f0",
  card: "#ffffff",
  cardMuted: "#f7ebea",
  cardWarm: "#f1e5e4",
  primary: "#874f4c",
  primarySoft: "#ffdad7",
  primarySoftDeep: "#fcb4b0",
  secondary: "#356572",
  secondarySoft: "#b7e7f7",
  tertiary: "#774f87",
  tertiarySoft: "#f8d8ff",
  warmCard: "#fffaf2",
  warmInput: "#fff4df",
  coolCard: "#f7f3fb",
  coolInput: "#eee9f4",
  text: "#201a1a",
  textMuted: "#524342",
  textSoft: "#847372",
  border: "#d7c2c0",
  white: "#ffffff",
  error: "#ba1a1a",

  surface: "#fff8f7",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#fdf1f0",
  surfaceContainer: "#f7ebea",
  surfaceContainerHigh: "#f1e5e4",
  onSurface: "#201a1a",
  onSurfaceVariant: "#524342",
  outline: "#847372",
  outlineVariant: "#d7c2c0",
  onPrimary: "#ffffff",
  primaryFixed: "#ffdad7",
  primaryFixedDim: "#fcb4b0",
};

export type AppColors = typeof colors;
